name = "medicalpkm"
main = "worker.js"
compatibility_date = "2024-01-01"

preview_urls = false

[[routes]]
pattern = "medicalpkm.com"
zone_name = "medicalpkm.com"
custom_domain = true

[[routes]]
pattern = "www.medicalpkm.com"
zone_name = "medicalpkm.com"
custom_domain = true
